# ROS 2 Sim-to-Real Robot Control: STAUBLI RX-160 Robot.
Configurations:

  - ID: "rx160_1"
    Name: "Staubli RX-160 on top of Robot Stand."
    urdf: "rx160.urdf.xacro"
    rob: "rx160"
    ee: "none"