cartesian_limits:
  max_trans_vel: 0.5
  max_trans_acc: 0.5
  max_trans_dec: 0.5
  max_rot_vel: 2.0

# These values have been increased slightly to improve linear planning success.
# Further tuning may be required, considering safety guidelines.