controller_names:
  - hande_controller

hande_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - robotiq_hande_left_finger_joint
    - robotiq_hande_right_finger_joint