# world_name: "empty"
world_name: "gas_station_3"
# origin: 
#     latitude: 40.4405287
#     longitude: -3.6898277
#     altitude: 100.0

origin: 
    latitude: 0.0
    longitude: 0.0
    altitude: 0.0
drones:
  - model_type: "quadrotor_base"
    model_name: "drone0"
    flight_time: 60
    xyz:
      - 0.0
      - 0.0
      - 0.3
    payload:
      - model_type: "gps"
        model_name: "gps"
      - model_type: "gimbal_speed"
        model_name: "gimbal"
        payload:
          model_type: "hd_camera"
          model_name: "camera"
      - model_type: "hd_camera"
        model_name: "down_camera"
        xyz: [0.1, 0.0, -0.05]
        rpy: [0.0, 1.57, 0.0]